compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-10-22"

name = "snappbiz-auth-worker"
main = "src/index.ts"

[observability]
enabled = true
head_sampling_rate = 1

[dev]
port = 3000

################# AUTH DEV SECTION #################
[[d1_databases]]
binding = "AuthDB" # Should match preview_database_id
database_name = "auth-dev"
database_id = "ca64f15c-a924-4bca-ad5f-62562f6eb02a" # wrangler d1 info YOUR_DATABASE_NAME
migrations_dir = "../../../packages/libs/auth/migrations/auth"
preview_database_id = "AuthDB" # A user-defined ID for your local test database.

[vars]
NODE_ENV = "development"
BACKEND_URL = "https://gw-dev.snappbiz.com"
JWT_ISSUER = "https://gw-dev.snappbiz.com/oidc"
JWT_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgvyW1iLTi4GRqIrbe
ugkFnBNflF5CCSZp4ZJ2V6AYKUihRANCAAQlM7y6KKxEnCnM12jKb0MYco369ZGI
F9PDDrdae5Wm++88rhbJTuyHOMiJbG9HUkHBklPpntfbaYqar47reNPn
-----END PRIVATE KEY-----
"""
################# END AUTH DEV SECTION #################
