compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-10-22"

name = "snappbiz-tenant-worker"
main = "src/index.ts"

[observability]
enabled = true
head_sampling_rate = 1

[dev]
port = 3002

################# TENANT DEV SECTION #################
[[d1_databases]]
binding = "TenantDB" # Should match preview_database_id
database_name = "tenant-dev"
database_id = "224734de-e396-4d4e-b9e3-97e1d9b5187b" # wrangler d1 info YOUR_DATABASE_NAME
migrations_dir = "../../../packages/drizzle/migrations/tenant"
preview_database_id = "TenantDB" # A user-defined ID for your local test database.

[vars]
NODE_ENV = "development"
BACKEND_URL = "https://gw-dev.snappbiz.com"
################# END TENANT DEV SECTION #################
